name: first-demo-pipeline

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches:
      - workflow-demo
  pull_request:

jobs:
  run_basc_taks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v3
      - name: Run Commands
        run: |
          echo "Hi I am testing this as part of my learning"
          echo "Check current working directoy"
          pwd
          echo "Check contents on current directory"
          ls -lart
      - name: Final Task
        run: echo "I am done testing!"
