name: manual-pipeline | Triggered By- ${{ github.actor }} | Branch- ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      branchname:
        description: Enter Branch Name t
        required: true
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string 
  push:
    branches:
      - main

jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          ref: ${{ inputs.branchname }}
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
      - name: Check environment variables
        run: |
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.actor }}
